import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  weight: "700",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/8e9f48c27b.js" crossOrigin="anonymous"></script>
      </head>
      <body
        className={`${montserrat.variable} font-sans font-bold antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
